### ISSUE TITLE
ProcessorManager默认线程池和RemotingProcessor线程池的设定需要在RpcServer.start()之后，应该在start()之前进行吧？

### ISSUE THREAD

**Issue by zhaojigang** [alipay/sofa-bolt#100]
### Your question

Processor默认线程池和RemotingProcessor线程池的设定需要在RpcServer.start()之后，代码如下：
```
RpcServer server = new RpcServer(8888);
server.start(); // 启动服务
server.registerDefaultExecutor(RpcProtocol.PROTOCOL_CODE, Executors.newCachedThreadPool());
server.registerDefaultExecutor(RpcProtocolV2.PROTOCOL_CODE, Executors.newCachedThreadPool());
server.registerProcessor(RpcProtocol.PROTOCOL_CODE, RpcCommandCode.RPC_REQUEST, new RpcRequestProcessor(Executors.newCachedThreadPool()));
```

如上这样使用，注册是需要发生在start()之后的，因为注册的代码需要用到ProccessorManager，在start()中的doInit()的时候，才会创建ProccessorManager。
如果注册必须发生在start()之后，那么如果在 RpcServer 启动之后并且在设置 registerDefaultExecutor 之前来了一个请求，请求的处理就放在原始的默认线程池去做了，与用户的初衷不同。

### Your advice
是不是我的使用姿势不对？如果确实是这样使用的，那么建议 RpcServer 的 init() 和 start() 应该分开，提供类似于如下的代码，这样我们就可以在 init() 之后进行线程池的设置了，设置完成之后再 start()。

```
init() {
  doInit();
}
startOnly() {
  doStart();
}
start() {
  init();
  startOnly();
}
```

### Environment

- SOFABolt version: 1.5.1
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
1. init方法之后会被移除（对外不可见），会统一组件的生命周期
2. “如果注册必须发生在start()之后，那么如果在 RpcServer 启动之后并且在设置 registerDefaultExecutor 之前来了一个请求，请求的处理就放在原始的默认线程池去做了，与用户的初衷不同。”通过统一生命周期之后，这块应该是在start之前就允许注册，预计是下一个版本。另外这里如果在start之后为注册之前接收到请求，这个请求只会输出一行错误日志。

**Comment by zhaojigang** [comment]
```
server.registerDefaultExecutor(RpcProtocol.PROTOCOL_CODE, Executors.newCachedThreadPool());
server.registerProcessor(RpcProtocol.PROTOCOL_CODE, RpcCommandCode.RPC_REQUEST, new RpcRequestProcessor(Executors.newCachedThreadPool()));
```
"另外这里如果在start之后为注册之前接收到请求，这个请求只会输出一行错误日志。" 这个情况对于registerDefaultExecutor应该不会出现，因为默认RpcServer.start()中已经创建了默认的 ProcessorManager#DefaultExecutor，我这里的代码只是覆盖已经创建的那个。对于registerProcessor当 RpcCommandCode 不是那三个的时候就会出现，但是这里我是 RPC_REQUEST，所以目的是去覆盖老的配置，来添加 RemotingProcessor级别的线程池，当我的这个没配置成功时，依然可以使用老的
![image](https://user-images.githubusercontent.com/14085645/46854563-d19a3b80-ce33-11e8-9e37-f757fe9aae5b.png)

**Comment by dbl-x** [comment]
“如果注册必须发生在start()之后，那么如果在 RpcServer 启动之后并且在设置 registerDefaultExecutor 之前来了一个请求，请求的处理就放在原始的默认线程池去做了，与用户的初衷不同。”

当前的实现确实是这样的，下一个版本会处理掉，将注册Processor\Executor和组件启动的关系整理清楚进行重构，预计在1.6.0版本
