### ISSUE TITLE
如何基于 ConfigItem 扩展自定义的配置项？

### ISSUE THREAD

**Issue by zhaojigang** [alipay/sofa-bolt#101]
### Your question

![image](https://user-images.githubusercontent.com/14085645/46913349-e4d91280-cfbd-11e8-9935-ffd30d264770.png)

1. 假设现在想增加一个自定义配置项 NETTY_TCP_NODELAY，由于 ConfigItem 是一个 enum 类，无法继承，这时候我们应该怎么添加一个自定义的的扩展项呢？

2. ConfigItem 和 Configs 类冗余，建议去掉 ConfigItem 类，
![image](https://user-images.githubusercontent.com/14085645/46913396-c889a580-cfbe-11e8-8d11-e15f3be8a74b.png)

ConfigContainer中的第二个参数用 Configs 中的String 来填充。

- SOFABolt version: 1.5.1 
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
目前这块是无法拓展的，如果需要拓展，需要修改源码。后续会将这个做成可配置。

**Comment by zhaojigang** [comment]
👌
