### ISSUE TITLE
ReconnectManager 可能重连线程不起作用？

### ISSUE THREAD

**Issue by zhaojigang** [alipay/sofa-bolt#103]
### Your question

1. retryWhenException 该方法中的 ReconnectManager.this.addReconnectTask(task); 是否需要try-catch包裹，否则，一旦抛出异常，重连线程会跑飞

2. 
```
    public ReconnectManager(ConnectionManager connectionManager) {
        this.connectionManager = connectionManager;
        this.healConnectionThreads = new Thread(new HealConnectionRunner());
        this.healConnectionThreads.start();
        this.started = true;
    }
```
this.started = true; 放在 this.healConnectionThreads.start(); 是否更合适，虽然，通常情况下都是  this.started = true; 先执行。万一 this.started = true; 后执行，那么 重连线程就不起作用了，重连任务直接退出了

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by zhaojigang** [comment]
![image](https://user-images.githubusercontent.com/14085645/47054957-75466b80-d1e7-11e8-9b70-7169a4369bef.png)

如果take失败，下边代码有可能报出空指针

**Comment by zhaojigang** [comment]
👌，我提个pr

**Comment by dbl-x** [comment]
https://github.com/alipay/sofa-bolt/pull/113
