### ISSUE TITLE
com.alipay.remoting.demo.RpcClientDemoByMain  # Logger是不是有问题

### ISSUE THREAD

**Issue by easonzhang1992** [alipay/sofa-bolt#111]
com.alipay.remoting.demo.RpcClientDemoByMain.java 
属性Logger=LoggerFactory.getLogger(BasicUsageDemoByJunit.class)

这里是写错了吗？在com.alipay.remoting.demo.RpcServerDemoByMain也有同样的情况

**Comment by khotyn** [comment]
@dbl-x 看起来应该使用当前类的 Class 获取 Logger？

@easonzhang1992 方便的话，可以直接给我们提一个 PR。

**Comment by dbl-x** [comment]
@khotyn 确实有问题。

@easonzhang1992 可以提交PR修复，会在1.6.0版本中修复demo代码的问题。

**Comment by easonzhang1992** [comment]
@dbl-x  @khotyn  已提PR

**Comment by dbl-x** [comment]
@easonzhang1992 已经合并，谢谢
