### ISSUE TITLE
请教bolt用来做im，适合么？

### ISSUE THREAD

**Issue by momsbaby** [alipay/sofa-bolt#118]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
SOFABolt是一个基于Netty的高性能的通信框架，你需要将同行框架贴合到你的具体的IM场景中再具体的考量。无法直接给答复是否适合你的IM需求。

**Comment by SpringStudent** [comment]
看了下sofa-bolt的demo，做IM应该是没啥问题的，发送IM消息可以看成sofa-bolt将请求传递给接收方，sofa-bolt本身支持连接管理，实现起来问题不大的。
