### ISSUE TITLE
管理Bolt默认的连接池实现的一点疑问？

### ISSUE THREAD

**Issue by wind-clothes** [alipay/sofa-bolt#124]
DefaultConnectionManager 连接池管理中的ConcurrentHashMap<String, RunStateRecordedFutureTask<ConnectionPool>> connTasks 的key是什么?然后就是ConnectionPool和Connection的对应关系是什么？

**Comment by dbl-x** [comment]
key是Connection的Url的uniqueKey   具体可以看一下Url的实现。
ConnectionPool可以理解为一个连接池，和Connection是1对N的关系
