### ISSUE TITLE
ConnectionSelectStrategy建议设计成可扩展和可配置

### ISSUE THREAD

**Issue by beston123** [alipay/sofa-bolt#128]
**Describe the solution you'd like**
1、ConnectionSelectStrategy建议设计成可扩展和可配置
2、RandomSelectStrategy中的random建议使用ThreadLocalRandom提高性能

**Comment by dbl-x** [comment]
1. ConnectionSelectStrategy可配置已经在1.6.0版本中支持：https://github.com/alipay/sofa-bolt/pull/138
2. 考虑到Bolt目前还要支持JDK1.6版本，所以这块保留使用Random
