### ISSUE TITLE
Change log encoding configuration

### ISSUE THREAD

**Issue by hongweiyi** [alipay/sofa-bolt#13]
BOLT use `-Dcom.alipay.remoting.client.log.encode` to control bolt framework log encoding, why not use `file.encoding` directly? Just like [sofa-rpc log-conf.xml](https://github.com/alipay/sofa-rpc/blob/master/extension-impl/log-common-tools/src/main/resources/com/alipay/sofa/rpc/log/log4j/log-conf.xml#L9), so developers can use one configuration to control all logs encoding.

**Comment by xmtsui** [comment]
good suggestion, will fix this in 1.4.2
