### ISSUE TITLE
com.alipay.remoting.rpc.DefaultInvokeFuture 类中的 CountDownLatch 是否可以使用 LockSupport  加上 volatile？

### ISSUE THREAD

**Issue by stateIs0** [alipay/sofa-bolt#17]
我看了 com.alipay.remoting.rpc.DefaultInvokeFuture  的相关代码，使用 CountDown 的代价是否有点大呢？如果使用 volatile 变量加上 LockSupport 是不是更轻量呢（貌似能够代替目前的功能？）？毕竟 AQS 还是挺重的。而且还需要实例化一个 CountDownLatch 对象。

**Comment by hellotimo** [comment]
hi，stateIs0，这个思路很有意思，可否提交 PR 和提供相应的性能对比数据？

**Comment by xmtsui** [comment]
issue closed because of overdue, you can reopen this if got any update.
