### ISSUE TITLE
sofa-bolt开源版本支持协程

### ISSUE THREAD

**Issue by SteNicholas** [alipay/sofa-bolt#35]
@xmtsui ，能否在开源版本上支持协程？据了解阿里AliJDK协程是按照JKU即http://ssw.jku.at/General/Staff/LS/coro/做的修改，所以能否把这块在sofa-bolt开源版本按照这个做个修改支持协程呢？

**Comment by xmtsui** [comment]
@SteNicholas

**Comment by xmtsui** [comment]
issue closed because of overdue, you can reopen this if got any update.
