### ISSUE TITLE
导入eclipse 报错

### ISSUE THREAD

**Issue by weir2010** [alipay/sofa-bolt#39]
: is an invalid character in resource name 'com.alipay.sofa:bolt'.
导入eclipse 报错

**Comment by weir2010** [comment]
myeclipse会 
sts不会
 不知道什么问题
截图怎么上传？

**Comment by khotyn** [comment]
@weir2010 编辑框 Ctrl+V 就可以了。

**Comment by liangyuanpeng** [comment]
@weir2010  把图片粘贴Ctrl+V到回复框就可以

**Comment by xmtsui** [comment]
临时先关闭了。有问题再沟通哈
