### ISSUE TITLE
ProtocolCodeBasedDecoder 相关问题

### ISSUE THREAD

**Issue by AJ-Liang** [alipay/sofa-bolt#40]
ProtocolCodeBasedDecoder
代码中没有校验报文的开始或结束符，万一报文有问题（例如报文错乱），那会不会一直导致误以为这连接对应的流还是可信的，一直在误读？

**Comment by xmtsui** [comment]
这个是复用了ByteToMessageDecoder，配合我们的协议设计来避免报文错乱的。即靠固定报文格式（可以看下RpcProtocolV2类）。如果报文有错乱，那么decode的过程会抛出异常，在后续的handler里复写了ChannelInboundHandlerAdapter#exceptionCaught方法，捕获异常后，会断开链接。

**Comment by xmtsui** [comment]
临时先关闭了。有问题再沟通哈
