### ISSUE TITLE
关于log

### ISSUE THREAD

**Issue by yolinkxzw** [alipay/sofa-bolt#41]
我在win7下使用IntelliJ IDEA运行程序，发现只能打印部分log。
不能打印log的java文件中Logger定义如下：
    private static final Logger    logger = LoggerFactory.getLogger(XXX.class); //其中XXX为java类名。
能打印log的java文件中Logger定义如下：
       private static final Logger  logger  = BoltLoggerFactory.getLogger("XXXXX");//其中XXX为log-conf.xml中定义的logger name。

请问：如果我需要看到所有的日志，该怎么做?

**Comment by liangyuanpeng** [comment]
可以具体举个例子，我运行了一下测试案例中的日志，一开始确实没有打印
``
private static final Logger logger = LoggerFactory.getLogger(XXX.class);
``
原因是因为我测试打印的级别是DEBUG，但是配置日志的最低级别是ERROR

**Comment by xmtsui** [comment]
当前所有内置的日志，都已经定义在log-conf里了，运行时，用户可以选择一种日志实现，依赖的alipay-common-tools组件，会自动加载对应实现的日志模板，来提供运行时的logger。这些内置日志固定打印在
`~/logs/bolt`目录。这里就是所有的日志了。

日志实现依赖参考：https://github.com/alipay/sofa-bolt/wiki/log_implementation_jar

另外，用户额外自己打印日志，自己再单独做log的配置即可。

**Comment by xmtsui** [comment]
临时先关闭了。有问题再沟通哈
