### ISSUE TITLE
epoll fully support wanted

### ISSUE THREAD

**Issue by eonezhang** [alipay/sofa-bolt#42]
### advice
As sofa-bolt build on top of `netty-4.1.25.Final`, and [netty 4 support epoll nativelly](http://netty.io/wiki/native-transports.html).
For performance, bolt should support epoll per user-like. 
So here I add an option `transport.use.epoll` so that user can determine whether enabled it or not under Linux system.

### Environment

- SOFABOLT version: v1.4.2
- OS version: Linux Family

**Comment by xmtsui** [comment]
same with #34
