### ISSUE TITLE
Wrong Demo : There isn't a class named "BoltServer" in sofa-bolt.

### ISSUE THREAD

**Issue by shibinfei** [alipay/sofa-bolt#49]
[This Demo](https://github.com/alipay/sofa-bolt/blob/master/src/test/java/com/alipay/remoting/demo/RpcServerDemoByMain.java) import `BoltServer` which not belong to sofa-bolt, it's a class in sofa-rpc.

**Comment by xmtsui** [comment]
* this demo BoltServer is in test module, you can find it in [test part](https://github.com/alipay/sofa-bolt/tree/master/src/test)

**Comment by shibinfei** [comment]
Oh, I see. Thanks a lot.
