### ISSUE TITLE
the size of a ArrayList should never be a negative number

### ISSUE THREAD

**Issue by thisisbaozi** [alipay/sofa-bolt#53]
see RandomSelectStrategy#select 

https://github.com/alipay/sofa-bolt/blob/2aabea02cacb7e134ac50cc1c965053fdb278bc7/src/main/java/com/alipay/remoting/RandomSelectStrategy.java#L78

**Comment by xmtsui** [comment]
Thanks for pointing this out, and are you interested to work on it?
