### ISSUE TITLE
demo服务端启动不起来

### ISSUE THREAD

**Issue by jimiyi** [alipay/sofa-bolt#67]
RpcServerDemoByMain 程序，启动报
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j ]
 INFO - Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j ]
server start failed!

**Comment by xmtsui** [comment]
看下是不是起了多个，端口冲突引起的。

**Comment by jimiyi** [comment]
还真是，主要是框架用了log4j2的日志，没打印出来，所以没看到错误信息

**Comment by xmtsui** [comment]
测试工程为了ci快一点，日志级别默认设置成了ERROR。辛苦手动改一下log的配置，改一下日志级别就能看到异常。

> 当前demo是放在测试工程里写的，后续我们看下怎么分开一下。

**Comment by khotyn** [comment]
@xmtsui 默认 Error 的错误级别的话，异常信息应该能够正常打印出来吧？

**Comment by xmtsui** [comment]
嗯，看了下，在~/logs/bolt里的error日志，是有的
![image](https://user-images.githubusercontent.com/1542690/42142648-1cbdb840-7de3-11e8-8162-1c5f74ed35d4.png)
