### ISSUE TITLE
Callback异步调用需要latch不是很方便

### ISSUE THREAD

**Issue by jimiyi** [alipay/sofa-bolt#68]
callback异步调用方式，必须和 final CountDownLatch latch结合使用，否则就会出现
com.alipay.remoting.exception.ConnectionClosedException: Connection closed when invoke with callback.The address is 127.0.0.1:8999
感觉不是很方便，这有什么改进方法么？

**Comment by xmtsui** [comment]
这个是不是在写单测？通常运行时服务端是常驻的，正常情况不会出现断链。
