### ISSUE TITLE
misuse of hashmap api cause warn log missing

### ISSUE THREAD

**Issue by xmtsui** [alipay/sofa-bolt#70]
## bug description
thx @yangli for pointing out these problems: 
![image](https://user-images.githubusercontent.com/1542690/42358697-8e497834-8110-11e8-8413-fbc3177832ad.png)
this bug is a mis-use of api, we should check key not value existed and then print warn log to notify user. 

## impact analysis
actually this bug have no bad impact except some warning log missing

**Comment by khotyn** [comment]
建议标题明确下到底是什么 Bug，一个 Issue 建议描述一个 Bug。

**Comment by xmtsui** [comment]
@khotyn ok, 已经修改
