### ISSUE TITLE
Android处理Bolt协议测试情况

### ISSUE THREAD

**Issue by walterlife** [alipay/sofa-bolt#75]
### 问题
Andorid端能否使用Bolt进行协议通讯

### 使用场景
长连接推送服务
实现细节:服务端使用Bolt作为远程通讯框架,Android通过TCP协议连接服务端,那么Android支持解析Bolt协议吗?

### Environment
- SOFABolt version: 1.4.2
- JVM version (JDK 8):
- OS version (CentOS7):
- Maven version: Maven 3
- IDE version: IDEA

**Comment by walterlife** [comment]
现在使用场景:
Client使用Socket连接使用Bolt实现的TCP Server,连接可以成功
在发送消息的时候,client消息可以发送成功,但是服务端的ConnectionEventHandler的close会触发,导致client收不到server的response 消息.
@xmtsui 麻烦大神帮忙看下

**Comment by xmtsui** [comment]
抱歉issue处理晚了。
####  问题1
当前bolt主要是用在内网环境，具备一定的网络容错能力（比如心跳保活、超时断开、断链重连等），但针对无线端的弱网环境，没有实际应用过，也没有做很好的测试覆盖。

另外，如果是无线端，需要把请求通过外网传输，此时加密、授权能机制是很重要的。现在bolt的协议暂时没有考虑这部分功能（主要是内网rpc、内网通信使用）。

#### 问题2
> client消息可以发送成功,但是服务端的ConnectionEventHandler的close会触发,导致client收不到server的response 消息.

这个正常场景不会，如果close事件触发的话，肯定是链接断开了（通常协议解包出错、网络不稳定、进程退出等原因）会导致断链然后close事件触发。

**Comment by xmtsui** [comment]
issue closed because of overdue, you can reopen this if got any update.
