### ISSUE TITLE
AbstractRemotingServer的stop操作预期只能执行一次，实际可以实现两次，与预期行为不符

### ISSUE THREAD

**Issue by dbl-x** [alipay/sofa-bolt#82]
**Describe the bug**
可以多次调用AbstractRemotingServer#stop，并没有抛出预期的IllegalStateException

### Expected behavior
第一次调用AbstractRemotingServer#stop，执行stop逻辑
第二次调用AbstractRemotingServer#stop，抛出IllegalStateException
### Actual behavior
第一次调用AbstractRemotingServer#stop，执行stop逻辑
第二次调用AbstractRemotingServer#stop，再次执行stop逻辑
第三次及之后调用AbstractRemotingServer#stop，抛出IllegalStateException
### Steps to reproduce
执行RemotingServerTest#testStopRepeatedly的单元测试
### Minimal yet complete reproducer code (or GitHub URL to code)
```
class AbstractRemotingServer
@Override
    public boolean stop() {
        // 逻辑或在前一个条件为true的情况下，不会之后后面的操作，所以第二次执行stop时started.compareAndSet(true, false)会返回true导致可以再次执行doStop
        if (inited.compareAndSet(true, false) || started.compareAndSet(true, false)) {
            return this.doStop();
        } else {
            throw new IllegalStateException("ERROR: The server has already stopped!");
        }
    }
```
### Environment

- SOFABolt version: 1.5.0 
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
另外，采用started和inited两个变量控制状态不是一个很好的做法；采用一个变量，拥有不同的状态可能是一个更好的做法，在各种控制逻辑上不容易出现BUG

**Comment by cytnju** [comment]
要不要在设计的时候添加一个destroy方法对应inited这个状态，在destroy方法中实现对于资源的释放，对应于init方法

**Comment by aCoder2013** [comment]
init是否应该设置为private，start方法会调用init方法，因此init设置成public会有点疑惑，另外文档也是没有调用init方法。这样的话就可以将状态改成一个枚举，`none-> initialized -> started`
